# OmegaWTK App Build Function

function(OmegaWTKApp)

    cmake_parse_arguments("_ARG" "" "NAME;BUNDLE_ID;ASSET_DIR;BUNDLE_ICON" "SOURCES;DEPS" ${ARGN})

    # Every opt-in component that was configured at WTK build time is
    # auto-linked into every app built via OmegaWTKApp(). Apps do not list
    # components in their own CMakeLists — selection happens once, at WTK
    # configure time, via the per-component OMEGAWTK_COMPONENT_<NAME>
    # flags. The GLOBAL property is populated by each component's
    # CMakeLists (see wtk/components/<name>/CMakeLists.txt).
    get_property(_OMEGAWTK_COMPONENT_TARGETS GLOBAL PROPERTY OMEGAWTK_COMPONENT_TARGETS)

    # =================================================================
    # Build the app's default.pak via omega-assetc.
    #
    # The bundle contains the compositor shader library (loaded by
    # PipelineRegistry::initialize at engine startup) plus every file
    # under ASSET_DIR. It ships next to the executable on Win/Linux and
    # inside Contents/Resources/ on macOS, where AppInst opens it via
    # an exe-relative path. Unencrypted for now — encryption is gated
    # behind a future per-app key.
    # =================================================================
    set(_pak_dir "${CMAKE_CURRENT_BINARY_DIR}/${_ARG_NAME}_pak")
    set(_pak_output "${_pak_dir}/default.pak")
    set(_pak_manifest "${_pak_dir}/manifest")
    file(MAKE_DIRECTORY "${_pak_dir}")

    set(_pak_asset_files "")
    if(_ARG_ASSET_DIR AND EXISTS "${_ARG_ASSET_DIR}")
        file(GLOB_RECURSE _pak_asset_files CONFIGURE_DEPENDS "${_ARG_ASSET_DIR}/*")
    endif()

    # Manifest is generated at configure time. Absolute paths sidestep
    # omega-assetc's manifest-dir-relative resolution; --strip-prefix
    # below trims them down to clean logical entry names.
    set(_pak_manifest_content "# Auto-generated by OmegaWTKApp(${_ARG_NAME}); do not edit.\n")
    string(APPEND _pak_manifest_content "${OMEGAWTK_COMPOSITOR_SHADER_LIB} type=shader\n")
    foreach(_pak_asset IN LISTS _pak_asset_files)
        string(APPEND _pak_manifest_content "${_pak_asset}\n")
    endforeach()

    # Only rewrite when content actually changed — otherwise every
    # reconfigure re-stamps the manifest and forces the pak to rebuild.
    set(_pak_manifest_existing "")
    if(EXISTS "${_pak_manifest}")
        file(READ "${_pak_manifest}" _pak_manifest_existing)
    endif()
    if(NOT "${_pak_manifest_content}" STREQUAL "${_pak_manifest_existing}")
        file(WRITE "${_pak_manifest}" "${_pak_manifest_content}")
    endif()

    set(_pak_strip_args "")
    if(_ARG_ASSET_DIR)
        list(APPEND _pak_strip_args "--strip-prefix" "${_ARG_ASSET_DIR}/")
    endif()
    get_filename_component(_pak_shader_dir "${OMEGAWTK_COMPOSITOR_SHADER_LIB}" DIRECTORY)
    list(APPEND _pak_strip_args "--strip-prefix" "${_pak_shader_dir}/")

    add_custom_command(
        OUTPUT "${_pak_output}"
        COMMAND $<TARGET_FILE:omega-assetc>
            --no-encrypt
            --manifest "${_pak_manifest}"
            ${_pak_strip_args}
            --output "${_pak_output}"
        DEPENDS
            omega-assetc
            OmegaWTKCompositorShaderLib
            "${_pak_manifest}"
            ${_pak_asset_files}
        VERBATIM
        COMMENT "Building ${_ARG_NAME}/default.pak")

    add_custom_target(${_ARG_NAME}_DefaultPak DEPENDS "${_pak_output}")

    if(TARGET_MACOS)
        set(BUNDLE_ID ${_ARG_BUNDLE_ID})
        set(APPNAME ${_ARG_NAME})
        set(BUNDLE_ICON ${_ARG_BUNDLE_ICON})
        configure_file(${OMEGAWTK_SOURCE_DIR}/target/macos/Info.plist.in ${CMAKE_CURRENT_BINARY_DIR}/Info.plist @ONLY)
        add_app_bundle(
            NAME ${_ARG_NAME}
            PLIST "${CMAKE_CURRENT_BINARY_DIR}/Info.plist"
            RESOURCES ${OMEGAWTK_SOURCE_DIR}/target/macos/MainMenu.nib ${_ARG_BUNDLE_ICON} ${_pak_output}
            DEPS OmegaWTK.framework OmegaGTE.framework ${_ARG_DEPS}
            EMBEDDED_FRAMEWORKS OmegaWTK OmegaGTE
            # Sibling dylibs the app exe + the embedded OmegaWTK/OmegaGTE
            # frameworks load at runtime. Copied into <App>.app/Contents/
            # Libraries/ so the bundle is self-contained — resolved via the
            # @executable_path/../Libraries rpath that add_app_bundle sets,
            # instead of referencing the build tree's lib/ dir. OmegaCommonImg
            # depends on OmegaCommonCore, and OmegaGTE/OmegaWTK/OmegaVA all
            # need Core (plus Img where the image codec is used).
            #
            # ${ICU_RUNTIME} (libicuuc/icudata/icui18n.dylib) is Core's own
            # runtime dependency — Core links ICU and loads it via @rpath at
            # startup. It is embedded next to Core here (already install-name
            # fixed to @rpath/@loader_path in common/CMakeLists.txt), so the
            # bundled Core finds ICU inside Contents/Libraries rather than the
            # build tree's icu/lib.
            EMBEDDED_LIBS OmegaCommonCore OmegaCommonImg OmegaVA ${ICU_RUNTIME}
            SOURCES ${_ARG_SOURCES})
        add_dependencies(${_ARG_NAME} OmegaWTK.framework ${_ARG_NAME}_DefaultPak)
        target_link_frameworks(${_ARG_NAME} OmegaGTE OmegaWTK)
        target_link_options(${_ARG_NAME} PRIVATE -rpath @loader_path/../Frameworks/OmegaWTK.framework/Libraries)
        target_link_libraries(${_ARG_NAME} PRIVATE OmegaVA)
        # Components are physically embedded inside OmegaWTK.framework's
        # Libraries/ dir via the framework's EMBEDDED_LIBS path, so the
        # rpath above already covers them. Link each so app code can call
        # the component's public surface.
        foreach(_comp IN LISTS _OMEGAWTK_COMPONENT_TARGETS)
            target_link_libraries(${_ARG_NAME} PRIVATE ${_comp})
        endforeach()
    else()
        add_executable(${_ARG_NAME} ${_ARG_SOURCES})
        add_dependencies(${_ARG_NAME} "OmegaWTK" ${_ARG_NAME}_DefaultPak)
        target_link_libraries(${_ARG_NAME} PUBLIC OmegaWTK)
        # Components ship as siblings of libOmegaWTK in the runtime output
        # dir; link each so the app's symbols resolve against them.
        # Loader/runtime staging is handled by omega_stage_runtime_dlls
        # (Win32) or the $ORIGIN rpath on the executable (Linux) further
        # down — both already see CMAKE_BINARY_DIR/bin and /lib.
        foreach(_comp IN LISTS _OMEGAWTK_COMPONENT_TARGETS)
            target_link_libraries(${_ARG_NAME} PRIVATE ${_comp})
        endforeach()
    endif()
    if(TARGET_MACOS)
        target_include_directories(${_ARG_NAME} PRIVATE "include" "gte/include" "gte/common/include" "${CMAKE_BINARY_DIR}/deps/icu/include")
        target_compile_definitions(${_ARG_NAME} PRIVATE TARGET_MACOS TARGET_METAL)
        target_sources(${_ARG_NAME} PRIVATE ${OMEGAWTK_SOURCE_DIR}/target/macos/main.mm)
    elseif(TARGET_WIN32)
        target_include_directories(${_ARG_NAME} PRIVATE "include" "gte/include" "gte/common/include" "${CMAKE_BINARY_DIR}/deps/icu/include")
        target_compile_definitions(${_ARG_NAME} PRIVATE OMEGAWTK_APP WINDOWS_PRIVATE TARGET_WIN32 TARGET_DIRECTX)
        set(EMBED "\"${OMEGAWTK_SOURCE_DIR}/target/win32/app.exe.manifest\"")
        configure_file(${OMEGAWTK_SOURCE_DIR}/target/win32/manifest.rc.in ${CMAKE_CURRENT_BINARY_DIR}/res.rc)
        # res.rc embeds app.exe.manifest by path, so the RC compiler reads the
        # manifest at compile time but CMake cannot infer that from the generated
        # res.rc. Declare it as an explicit object dependency so editing
        # app.exe.manifest forces the resource (and thus the EXE's embedded
        # manifest) to rebuild; otherwise an incremental build silently keeps the
        # stale manifest baked into the binary.
        set_source_files_properties(${CMAKE_CURRENT_BINARY_DIR}/res.rc PROPERTIES
            OBJECT_DEPENDS "${OMEGAWTK_SOURCE_DIR}/target/win32/app.exe.manifest")
        target_sources(${_ARG_NAME} PRIVATE ${OMEGAWTK_SOURCE_DIR}/target/win32/mmain.cpp ${CMAKE_CURRENT_BINARY_DIR}/res.rc)
        target_link_options(${_ARG_NAME} PRIVATE /SUBSYSTEM:CONSOLE /ENTRY:WinMainCRTStartup /MANIFEST:NO)

        # OmegaCommon, OmegaWTK, OmegaGTE land in ${CMAKE_BINARY_DIR}/bin/
        # as their own RUNTIME_OUTPUT_DIRECTORY. Their shared third-party
        # DLLs (ICU via OmegaCommon, libxml2 via OmegaWTK) are staged into
        # the same dir as POST_BUILD steps on each module. Fan all of them
        # out into the app's output dir in one go:
        omega_stage_runtime_dlls(${_ARG_NAME})

        # The app's default.pak (compositor shader lib + ASSET_DIR
        # contents) ships next to the exe; AppInst opens it at startup.
        add_custom_command(TARGET ${_ARG_NAME} POST_BUILD
            COMMAND ${CMAKE_COMMAND} -E copy
                "${_pak_output}"
                "$<TARGET_FILE_DIR:${_ARG_NAME}>/default.pak")
    elseif(TARGET_LINUX)
        target_include_directories(${_ARG_NAME} PRIVATE "include" "gte/include" "gte/common/include" "${CMAKE_BINARY_DIR}/deps/icu/include")
        target_compile_definitions(${_ARG_NAME} PRIVATE OMEGAWTK_APP TARGET_GTK TARGET_VULKAN)
        # libOmegaWTK.so pulls in ffmpeg, which drags in system libavformat/librsvg.
        # Those expect versioned libxml2 symbols (LIBXML2_2.4.30, etc.) that the
        # bundled libxml2.so does not expose. Defer indirect-library symbol
        # resolution to the runtime loader, which finds the system libxml2.
        target_link_options(${_ARG_NAME} PRIVATE "-Wl,--allow-shlib-undefined")
        target_sources(${_ARG_NAME} PRIVATE ${OMEGAWTK_SOURCE_DIR}/target/gtk/main.cpp)
        add_custom_command(TARGET ${_ARG_NAME} POST_BUILD
            COMMAND ${CMAKE_COMMAND} -E copy "${_pak_output}" "$<TARGET_FILE_DIR:${_ARG_NAME}>/default.pak")
    endif()
endfunction()
