#include "AST.def"
#include "CodeGen.h"
#include <sstream>
#include <algorithm>
#include <cstdint>
#include <cstring>
#include <iomanip>
#include <iostream>
#include <string>

#define GLSL_HEADER "// Warning! This file has been generated by omegaslc! DO NOT EDIT!!\n#version 450\n#extension GL_EXT_samplerless_texture_functions : enable"

#define GLSL_VERTEX_ID "gl_VertexIndex"
#define GLSL_POSITION "gl_Position"
#define GLSL_GLOBAL_THREAD_ID "gl_GlobalInvocationID"
#define GLSL_LOCAL_THREAD_ID "gl_LocalInvocationID"
#define GLSL_THREADGROUP_ID "gl_WorkGroupID"
#define GLSL_IMAGE1D "image1D"
#define GLSL_IMAGE2D "image2D"
#define GLSL_IMAGE3D "image3D"
#define GLSL_TEXTURE1D "texture1D"
#define GLSL_TEXTURE2D "texture2D"
#define GLSL_TEXTURE3D "texture3D"


namespace omegasl {

    /// Print a float literal so it cannot be misread as an integer literal.
    /// Why: ostream << float drops a trailing `.0`, so a source `0.0` becomes
    /// `0` in the generated shader. GLSL is the strictest of the three
    /// targets here — `max(float, 0)` is a hard type error, not just an
    /// overload-ambiguity warning.
    static std::string formatFloatLit(double v) {
        std::ostringstream os;
        os << std::setprecision(9) << v;
        std::string s = os.str();
        if (s.find_first_of(".eEnN") == std::string::npos) {
            s += ".0";
        }
        return s;
    }

    /// Prefix identifiers that collide with GLSL reserved words.
    static inline void writeGLSLIdent(const OmegaCommon::StrRef &name, std::ostream &out) {
        if (name == "input" || name == "output" ||
            name == "shared" || name == "filter" ||
            name == "common" || name == "partition" ||
            name == "active" || name == "resource") {
            out << "_";
        }
        out.write(name.data(), name.size());
    }

    class GLSLCodeGen : public CodeGen {

        std::ostream & shaderOut;
        std::ofstream fileOut;
        std::ostringstream stringOut;

        GLSLCodeOpts &glslCodeOpts;

        /// Typed accessor for the fragment-output / internal-struct state
        /// that lives on `GLSLTarget` after Phase 8a. The base `target`
        /// is `std::unique_ptr<Target>`; downcast once via this helper
        /// so the populator/reader sites scattered through SHADER_DECL
        /// processing stay readable.
        GLSLTarget &glslTarget() {
            return static_cast<GLSLTarget &>(*target);
        }

        void emitUserFunctionSignature(ast::FuncDecl *f){
            writeTypeExpr(f->returnType, shaderOut);
            shaderOut << " " << spellUserFuncName(f->name) << "(";
            for(size_t i = 0; i < f->params.size(); i++){
                if(i > 0) shaderOut << ", ";
                writeTypeExpr(f->params[i].typeExpr, shaderOut);
                shaderOut << " " << f->params[i].name;
            }
            shaderOut << ")";
        }

        void emitUserFunctionPrototype(ast::FuncDecl *f){
            emitUserFunctionSignature(f);
            shaderOut << ";" << std::endl;
        }

        void emitUserFunction(ast::FuncDecl *f){
            emitUserFunctionSignature(f);
            shaderOut << std::endl;
            generateBlock(*f->block);
            shaderOut << std::endl;
        }

    public:
        explicit GLSLCodeGen(CodeGenOpts &opts,GLSLCodeOpts &glslCodeOpts): CodeGen(opts, std::make_unique<GLSLTarget>(glslCodeOpts)), shaderOut(fileOut),glslCodeOpts(glslCodeOpts){
        }
        explicit GLSLCodeGen(CodeGenOpts &opts,GLSLCodeOpts & glslCodeOpts,std::ostringstream & stringOut):
                CodeGen(opts, std::make_unique<GLSLTarget>(glslCodeOpts)),shaderOut(this->stringOut), stringOut(std::move(stringOut)),glslCodeOpts(glslCodeOpts){
        }

        inline void writeTypeExpr(ast::TypeExpr *typeExpr,std::ostream & out) {
            target->writeTypeName(typeResolver->resolveTypeWithExpr(typeExpr), typeExpr->pointer, out);
        }

        void generateDecl(ast::Decl *decl) override{
            switch (decl->type) {
                case RESOURCE_DECL: {
                    resourceStore.add((ast::ResourceDecl *)decl);
                    break;
                }
                case IF_STMT : {
                    auto _stmt = (ast::IfStmt *)decl;
                    shaderOut << "if(";
                    generateExpr(_stmt->condition);
                    shaderOut << ")";
                    generateBlock(*_stmt->thenBlock);
                    for(auto & branch : _stmt->elseIfs){
                        shaderOut << " else if(";
                        generateExpr(branch.condition);
                        shaderOut << ")";
                        generateBlock(*branch.block);
                    }
                    if(_stmt->elseBlock){
                        shaderOut << " else ";
                        generateBlock(*_stmt->elseBlock);
                    }
                    break;
                }
                case FOR_STMT : {
                    auto _stmt = (ast::ForStmt *)decl;
                    shaderOut << "for(";
                    if(_stmt->init){ generateDecl((ast::Decl *)_stmt->init); }
                    shaderOut << ";";
                    if(_stmt->condition){ generateExpr(_stmt->condition); }
                    shaderOut << ";";
                    if(_stmt->increment){ generateExpr(_stmt->increment); }
                    shaderOut << ")";
                    generateBlock(*_stmt->body);
                    break;
                }
                case WHILE_STMT : {
                    auto _stmt = (ast::WhileStmt *)decl;
                    shaderOut << "while(";
                    generateExpr(_stmt->condition);
                    shaderOut << ")";
                    generateBlock(*_stmt->body);
                    break;
                }
                case BREAK_STMT : {
                    shaderOut << "break";
                    break;
                }
                case CONTINUE_STMT : {
                    shaderOut << "continue";
                    break;
                }
                case DISCARD_STMT : {
                    auto kw = target->discardStatement();
                    shaderOut << kw;
                    break;
                }
                case STRUCT_DECL : {
                    auto _decl = (ast::StructDecl *)decl;

                    std::ostringstream out;
                    /// Write Internal Struct as seperate parameters
                    if(_decl->internal){
                        glslTarget().internalStructs.push_back(_decl);
                    }
                    else {
                        out << "struct " << _decl->name << " {" << std::endl;
                        for (auto &f: _decl->fields) {
                            out << "  ";
                            writeTypeExpr(f.typeExpr, out);
                            out << " " << f.name << ";" << std::endl;
                        }
                        out << "};";
                    }
                    glslTarget().generatedStructs.insert(std::make_pair(_decl->name, out.str()));
                    glslTarget().structDeclMap[_decl->name] = _decl;

                    break;
                }
                case RETURN_DECL : {
                    auto _decl = (ast::ReturnDecl *)decl;
                    if(_decl->expr && glslTarget().currentShaderType == ast::ShaderDecl::Fragment
                       && glslTarget().fragmentOutputStruct != nullptr){
                        /// Struct-returning fragment in a nested block: per-field
                        /// stores already happened, so just `return;`.
                        shaderOut << "return";
                    }
                    else if(_decl->expr && glslTarget().currentShaderType == ast::ShaderDecl::Fragment
                       && !glslTarget().activeReturnReplacement.empty()){
                        // Fragment shader: main() is void in GLSL, so
                        // `return expr;` becomes `_outColor = expr; return;`
                        shaderOut << glslTarget().activeReturnReplacement << " = ";
                        generateExpr(_decl->expr);
                        shaderOut << ";" << std::endl;
                        for(unsigned i = 0;i < indentLevel;i++){
                            shaderOut << "  ";
                        }
                        shaderOut << "return";
                    }
                    else if(_decl->expr){
                        shaderOut << "return ";
                        generateExpr(_decl->expr);
                    }
                    else {
                        shaderOut << "return";
                    }
                    break;
                }
                case VAR_DECL : {
                    auto _decl = (ast::VarDecl *)decl;
                    auto pred = [&](ast::StructDecl * decl) -> bool{
                        return decl->name == _decl->typeExpr->name;
                    };
                    auto internal_struct_found = std::find_if(glslTarget().internalStructs.begin(),glslTarget().internalStructs.end(),pred);
                    if(internal_struct_found == glslTarget().internalStructs.end()) {
                        // Write Normal Var Decl if not internal struct
                        writeTypeExpr(_decl->typeExpr, shaderOut);
                        shaderOut << " " << _decl->spec.name;
                        if(_decl->typeExpr->arraySize.has_value()){
                            shaderOut << "[" << _decl->typeExpr->arraySize.value() << "]";
                        }
                        if (_decl->spec.initializer.has_value()) {
                            shaderOut << " = " << std::flush;
                            generateExpr(_decl->spec.initializer.value());
                        }
                    }
                    else {
                        /// Track variable with internal struct
                        glslTarget().internalStructVarMap.push_back(std::make_pair(_decl->spec.name,*internal_struct_found));

                        /// If the declaration has a brace initializer (ARRAY_EXPR),
                        /// decompose it into assignments to gl_Position and output
                        /// varyings.  Without this, `Raster r = { pos, uv };` would
                        /// silently drop the initializer and leave gl_Position unset.
                        if(_decl->spec.initializer.has_value() &&
                           _decl->spec.initializer.value()->type == ARRAY_EXPR){
                            auto *initList = (ast::ArrayExpr *)_decl->spec.initializer.value();
                            auto *structDecl = *internal_struct_found;
                            size_t count = std::min(initList->elm.size(), structDecl->fields.size());
                            for(size_t fi = 0; fi < count; fi++){
                                for(unsigned i = 0;i < indentLevel;i++){
                                    shaderOut << "  ";
                                }
                                auto &field = structDecl->fields[fi];
                                glslTarget().writeInternalFieldRef(field, structDecl->name, shaderOut);
                                shaderOut << " = ";
                                generateExpr(initList->elm[fi]);
                                shaderOut << ";" << std::endl;
                            }
                        }
                    }
                    break;
                }
                case FUNC_DECL : {
                    auto *_fd = (ast::FuncDecl *)decl;
                    userFuncDecls.push_back(_fd);
                    userFuncNames.insert(std::string(_fd->name));
                    break;
                }
                case SHADER_DECL : {
                    auto _decl = (ast::ShaderDecl *)decl;

                    if (opts.runtimeCompile) {
                        stringOut.str("");
                    } else {
                        auto p = OmegaCommon::FS::Path(opts.tempDir).append(_decl->name)
                                     .concat(target->shaderFileExt(_decl->shaderType)).str();
                        fileOut.open(p);
                    }

                    shaderOut << GLSL_HEADER << std::endl;

                    /// Prototypes first (dedup by name), then bodies — supports
                    /// forward declarations and calls between user functions
                    /// regardless of definition order.
                    {
                        OmegaCommon::Map<OmegaCommon::String, int> emittedProtos;
                        for (auto *uf : userFuncDecls) {
                            if (emittedProtos.find(uf->name) != emittedProtos.end()) continue;
                            emittedProtos.insert(std::make_pair(uf->name, 0));
                            emitUserFunctionPrototype(uf);
                        }
                    }
                    for (auto *uf : userFuncDecls) {
                        if (uf->isForwardDecl) continue;
                        emitUserFunction(uf);
                    }

                    omegasl_shader shader_entry{};
                    target->emitShaderEntryHeader(*this, _decl, shader_entry, shaderOut);
                    target->emitShaderEntryBody(*this, _decl, shader_entry, shaderOut);

                    OmegaCommon::String object_file;
                    if (!opts.runtimeCompile) {
                        object_file = OmegaCommon::FS::Path(opts.tempDir).append(_decl->name).concat(".spv").absPath();
                        fileOut.close();
                    } else {
                        object_file = _decl->name;
                    }
                    shaderMap.insert(std::make_pair(object_file, shader_entry));
                    break;
                }
            }
        }
        std::ostream &shaderOutStream() override { return shaderOut; }
        bool compileShader(ast::ShaderDecl::Type type, const OmegaCommon::StrRef &name, const OmegaCommon::FS::Path &path, const OmegaCommon::FS::Path &outputPath) override {
            return target->compileShader(type, name, path, outputPath);
        }
        void compileShaderOnRuntime(ast::ShaderDecl::Type type, const OmegaCommon::StrRef &name) override {
            auto &shader_entry = shaderMap[name.data()];
            target->compileShaderRuntime(type, name, stringOut.str(), shader_entry);
        }
        ~GLSLCodeGen() override = default;
    };

    std::shared_ptr<CodeGen> GLSLCodeGenMake(CodeGenOpts & opts,GLSLCodeOpts &glslCodeOpts){
        return std::make_shared<GLSLCodeGen>(opts,glslCodeOpts);
    }

    std::shared_ptr<CodeGen> GLSLCodeGenMakeRuntime(CodeGenOpts &opts,GLSLCodeOpts &glslCodeOpts,std::ostringstream &out){
        return std::make_shared<GLSLCodeGen>(opts,glslCodeOpts,out);
    }
}
