#include "CodeGen.h"
#include <iomanip>
#include <set>
#include <sstream>
#include <string>



namespace omegasl {

    /// Print a float literal so it cannot be misread as an integer literal.
    /// Why: ostream << float drops a trailing `.0`, so a source `0.0` becomes
    /// `0` in the generated shader. Metal/HLSL/GLSL all have integer overloads
    /// for `max`/`min`/`clamp`/etc., and an integer-shaped argument makes
    /// `max(float, 0)` ambiguous on Metal and a hard type error on GLSL.
    static std::string formatFloatLit(double v) {
        std::ostringstream os;
        os << std::setprecision(9) << v;
        std::string s = os.str();
        if (s.find_first_of(".eEnN") == std::string::npos) {
            s += ".0";
        }
        return s;
    }

    const char defaultHeaders[] = R"(// Warning! This file was generated by omegaslc
#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

)";

    class MetalCodeGen : public CodeGen {

        std::ostringstream stringOut;
        std::ofstream fileOut;

        std::ostream & shaderOut;

        std::map<std::string,std::string> generatedFuncs;
        std::map<std::string,std::string> generatedStructs;

        void emitUserFunctionSignature(ast::FuncDecl *f){
            writeTypeExpr(f->returnType, shaderOut);
            shaderOut << " " << spellUserFuncName(f->name) << "(";
            for(size_t i = 0; i < f->params.size(); i++){
                if(i > 0) shaderOut << ", ";
                writeTypeExpr(f->params[i].typeExpr, shaderOut);
                shaderOut << " " << f->params[i].name;
            }
            shaderOut << ")";
        }

        void emitUserFunctionPrototype(ast::FuncDecl *f){
            emitUserFunctionSignature(f);
            shaderOut << ";" << std::endl;
        }

        void emitUserFunction(ast::FuncDecl *f){
            emitUserFunctionSignature(f);
            shaderOut << std::endl;
            generateBlock(*f->block);
            shaderOut << std::endl;
        }

        MetalCodeOpts & metalCodeOpts;

    public:
        explicit MetalCodeGen(CodeGenOpts &opts,MetalCodeOpts & metalCodeOpts):
        CodeGen(opts, std::make_unique<MSLTarget>(metalCodeOpts)),shaderOut(fileOut),metalCodeOpts(metalCodeOpts){

        }
        explicit MetalCodeGen(CodeGenOpts &opts,MetalCodeOpts & metalCodeOpts,std::ostringstream & stringOut):
                CodeGen(opts, std::make_unique<MSLTarget>(metalCodeOpts)), stringOut(std::move(stringOut)),shaderOut(this->stringOut),metalCodeOpts(metalCodeOpts){

        }
        ~MetalCodeGen() override = default;
        inline void writeTypeExpr(ast::TypeExpr *t,std::ostream & out){
            target->writeTypeName(typeResolver->resolveTypeWithExpr(t), t->pointer, out);
        }
        std::ostream &shaderOutStream() override { return shaderOut; }
        void generateDecl(ast::Decl *decl) override {
            switch (decl->type) {
                case VAR_DECL : {
                    auto *_decl = (ast::VarDecl *)decl;
                    writeTypeExpr(_decl->typeExpr,shaderOut);
                    shaderOut << " " << _decl->spec.name;
                    if(_decl->typeExpr->arraySize.has_value()){
                        shaderOut << "[" << _decl->typeExpr->arraySize.value() << "]";
                    }
                    if(_decl->spec.initializer.has_value()){
                        shaderOut << " = ";
                        generateExpr(_decl->spec.initializer.value());
                    }
                    break;
                }
                case RETURN_DECL : {
                    auto *_decl = (ast::ReturnDecl *)decl;
                    if(_decl->expr){
                        shaderOut << "return ";
                        generateExpr(_decl->expr);
                    }
                    else {
                        shaderOut << "return";
                    }
                    break;
                }
                case IF_STMT : {
                    auto *_stmt = (ast::IfStmt *)decl;
                    shaderOut << "if(";
                    generateExpr(_stmt->condition);
                    shaderOut << ")";
                    generateBlock(*_stmt->thenBlock);
                    for(auto & branch : _stmt->elseIfs){
                        shaderOut << " else if(";
                        generateExpr(branch.condition);
                        shaderOut << ")";
                        generateBlock(*branch.block);
                    }
                    if(_stmt->elseBlock){
                        shaderOut << " else ";
                        generateBlock(*_stmt->elseBlock);
                    }
                    break;
                }
                case FOR_STMT : {
                    auto *_stmt = (ast::ForStmt *)decl;
                    shaderOut << "for(";
                    if(_stmt->init){ generateDecl((ast::Decl *)_stmt->init); }
                    shaderOut << ";";
                    if(_stmt->condition){ generateExpr(_stmt->condition); }
                    shaderOut << ";";
                    if(_stmt->increment){ generateExpr(_stmt->increment); }
                    shaderOut << ")";
                    generateBlock(*_stmt->body);
                    break;
                }
                case WHILE_STMT : {
                    auto *_stmt = (ast::WhileStmt *)decl;
                    shaderOut << "while(";
                    generateExpr(_stmt->condition);
                    shaderOut << ")";
                    generateBlock(*_stmt->body);
                    break;
                }
                case BREAK_STMT : {
                    shaderOut << "break";
                    break;
                }
                case CONTINUE_STMT : {
                    shaderOut << "continue";
                    break;
                }
                case DISCARD_STMT : {
                    auto kw = target->discardStatement();
                    shaderOut << kw;
                    break;
                }
                case RESOURCE_DECL : {
                    auto *_decl = (ast::ResourceDecl *)decl;
                    resourceStore.add(_decl);
                    break;
                }
                case FUNC_DECL : {
                    auto *_fd = (ast::FuncDecl *)decl;
                    userFuncDecls.push_back(_fd);
                    userFuncNames.insert(std::string(_fd->name));
                    break;
                }
                case STRUCT_DECL : {
                    auto *_decl = (ast::StructDecl *)decl;
                    std::ostringstream out;
                    out << "struct " << _decl->name << " {" << std::endl;
                    for(auto p : _decl->fields){
                        out << "    ";
                        writeTypeExpr(p.typeExpr,out);
                        out << " " << p.name;
                        if(p.attributeName.has_value()){
                            /// Plain `Color` (no index) and `TexCoord` are
                            /// vertex→fragment varyings; MSL leaves them
                            /// untagged on the struct. `Color(N)`, `Depth`,
                            /// and other fragment-output / Metal-specific
                            /// semantics get an `[[...]]` qualifier.
                            bool isBareColor = (p.attributeName.value() == ATTRIBUTE_COLOR
                                                && !p.attributeIndex.has_value());
                            bool isTexCoord  = (p.attributeName.value() == ATTRIBUTE_TEXCOORD);
                            if(!isBareColor && !isTexCoord){
                                out << "[[";
                                target->writeAttribute(p.attributeName.value(),p.attributeIndex,out);
                                out << "]]";
                            }
                        }
                        out << ";" << std::endl;
                    }
                    out << "};" << std::endl;

                    generatedStructs.insert(std::make_pair(_decl->name,out.str()));
                    break;
                }
                case SHADER_DECL : {
                    auto *_decl = (ast::ShaderDecl *)decl;

                    /// Phase 9: stage-support gate is owned by the target.
                    /// Metal still refuses hull/domain (see
                    /// OmegaSL-Reference.md bug 3) — the diagnostic comes
                    /// back through the out parameter.
                    std::string supportDiag;
                    if (!target->supportsStage(_decl->shaderType, supportDiag)) {
                        std::cerr << "error: " << supportDiag << " ('" << _decl->name << "')" << std::endl;
                        hasFatalErrors = true;
                        break;
                    }

                    OmegaCommon::String object_file;

                    if(opts.runtimeCompile){
                        object_file = _decl->name;
                        stringOut.str("");
                    }
                    else {
                        object_file =  OmegaCommon::FS::Path(opts.tempDir).append(_decl->name).concat(".metallib").absPath();
                        fileOut.open(OmegaCommon::FS::Path(opts.tempDir).append(_decl->name).concat(target->shaderFileExt(_decl->shaderType)).str(),
                                     std::ios::out);
                    }

                    shaderOut << defaultHeaders;

                    /// Prototypes first (dedup by name), then bodies — this
                    /// supports forward declarations and calls between user
                    /// functions regardless of definition order.
                    {
                        OmegaCommon::Map<OmegaCommon::String, int> emittedProtos;
                        for(auto *uf : userFuncDecls){
                            if(emittedProtos.find(uf->name) != emittedProtos.end())
                                continue;
                            emittedProtos.insert(std::make_pair(uf->name, 0));
                            emitUserFunctionPrototype(uf);
                        }
                    }
                    for(auto *uf : userFuncDecls){
                        if(uf->isForwardDecl)
                            continue;
                        emitUserFunction(uf);
                    }

                    std::vector<std::string> used_type_list;
                    typeResolver->getStructsInFuncDecl(_decl,used_type_list);

                    if(!used_type_list.empty()){
                        for(auto & t : used_type_list){
                            shaderOut << generatedStructs[t] << std::endl << std::endl;
                        }
                    }

                    /// Phase 8d: function signature + body delegated to
                    /// `MSLTarget`. Header writes the stage decorator and
                    /// `(<resources, params>)`; body writes `{`, flushes
                    /// static samplers, walks the user block, and closes.
                    omegasl_shader shadermap_entry {};
                    target->emitShaderEntryHeader(*this, _decl, shadermap_entry, shaderOut);
                    target->emitShaderEntryBody(*this, _decl, shadermap_entry, shaderOut);

                    shaderMap.insert(std::make_pair(object_file,shadermap_entry));

                    if(opts.runtimeCompile){

                    }
                    else {
                        fileOut.close();
                    }
                    break;
                }
                default : {
                    break;
                }
            }
        }
        bool compileShader(ast::ShaderDecl::Type type, const OmegaCommon::StrRef &name, const OmegaCommon::FS::Path &path,const OmegaCommon::FS::Path & outputPath) override {
            return target->compileShader(type, name, path, outputPath);
        }
        void compileShaderOnRuntime(ast::ShaderDecl::Type type,const OmegaCommon::StrRef &name) override {
            OmegaCommon::String shaderName{name.begin(), name.end()};
            auto shaderIt = shaderMap.find(shaderName);
            if (shaderIt == shaderMap.end()) {
                std::cout << "Runtime compile: shader entry not found for `" << shaderName << "`" << std::endl;
                return;
            }
            target->compileShaderRuntime(type, name, stringOut.str(), shaderIt->second);
        }
    };

    std::shared_ptr<CodeGen> MetalCodeGenMake(CodeGenOpts &opts,MetalCodeOpts &metalCodeOpts){
        return std::make_shared<MetalCodeGen>(opts,metalCodeOpts);
    };

    std::shared_ptr<CodeGen> MetalCodeGenMakeRuntime(CodeGenOpts &opts,MetalCodeOpts &metalCodeOpts,std::ostringstream & out){
        return std::make_shared<MetalCodeGen>(opts,metalCodeOpts,out);
    };
}
