from __future__ import annotations

import os
import re
from pathlib import Path

from .errors import ManifestValidationError


_CMAKE_IDENTIFIER_PATTERN = re.compile(r"[^A-Za-z0-9]+")


def cmake_identifier(value: str, *, manifest_path: str, field: str) -> str:
    normalized = _CMAKE_IDENTIFIER_PATTERN.sub("_", value).strip("_").upper()
    if not normalized:
        raise ManifestValidationError(
            f"unable to derive a CMake identifier from '{value}'",
            manifest_path=manifest_path,
            field=field,
        )
    if normalized[0].isdigit():
        normalized = f"_{normalized}"
    return normalized


def _cmake_escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace("\"", "\\\"").replace(";", "\\;")


def render_cmake_exports(state: dict, manifest_projects: dict[str, str | None]) -> str:
    dependencies = state.get("dependencies", {})
    if not isinstance(dependencies, dict):
        dependencies = {}

    lines = [
        "# Generated by autom-deps. Do not edit.",
        "",
    ]
    assignments: list[tuple[str, str]] = []

    for entry in dependencies.values():
        if not isinstance(entry, dict):
            continue

        exports = entry.get("exports", {})
        if not isinstance(exports, dict) or not exports:
            continue

        manifest_path = str(entry.get("manifest", ""))
        project = manifest_projects.get(manifest_path)
        if not isinstance(project, str) or not project:
            raise ManifestValidationError(
                "CMake export generation requires a top-level 'project' field in each manifest with exports",
                manifest_path=manifest_path or None,
                field="project",
            )

        project_identifier = cmake_identifier(
            project,
            manifest_path=manifest_path,
            field="project",
        )

        for export_name, export_value in sorted(exports.items()):
            if not isinstance(export_name, str) or not isinstance(export_value, str):
                continue
            export_identifier = cmake_identifier(
                export_name,
                manifest_path=manifest_path,
                field="exports",
            )
            assignments.append(
                (
                    f"{project_identifier}_{export_identifier}",
                    export_value,
                )
            )

    for variable_name, value in sorted(assignments):
        lines.append(f"set({variable_name} \"{_cmake_escape(value)}\")")

    lines.append("")
    return "\n".join(lines)


def write_cmake_exports(path: str | Path, state: dict, manifest_projects: dict[str, str | None]) -> None:
    output_path = Path(path)
    if not output_path.is_absolute():
        output_path = output_path.resolve()

    output_path.parent.mkdir(parents=True, exist_ok=True)
    temp_path = output_path.with_suffix(output_path.suffix + ".tmp")
    temp_path.write_text(render_cmake_exports(state, manifest_projects), encoding="utf-8")
    os.replace(temp_path, output_path)
