<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>OmegaSL</string>
	<key>scopeName</key>
	<string>source.omegasl</string>
	<key>fileTypes</key>
	<array>
		<string>omegasl</string>
	</array>
	<key>foldingStartMarker</key>
	<string>\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>^\s*\}</string>
	<key>uuid</key>
	<string>0c7af5c0-ded7-44af-8b49-15e3e0203d8f</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#preprocessor</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#strings</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#numbers</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#shader-declarations</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#struct-declarations</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#resource-declarations</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#resource-map</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#attributes</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keywords</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#types</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#builtins</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#constants</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#member-access</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#function-calls</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#operators</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#punctuation</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>comment.line.double-slash.omegasl</string>
					<key>match</key>
					<string>//.*$</string>
				</dict>
				<dict>
					<key>name</key>
					<string>comment.block.omegasl</string>
					<key>begin</key>
					<string>/\*</string>
					<key>end</key>
					<string>\*/</string>
				</dict>
			</array>
		</dict>
		<key>preprocessor</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.preprocessor.omegasl</string>
					<key>begin</key>
					<string>^\s*(#)\s*(define|ifdef|ifndef|endif|include)\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.preprocessor.omegasl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.control.import.omegasl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#strings</string>
						</dict>
						<dict>
							<key>name</key>
							<string>entity.name.function.preprocessor.omegasl</string>
							<key>match</key>
							<string>\b[A-Za-z_][A-Za-z0-9_]*\b</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>string.quoted.double.omegasl</string>
					<key>begin</key>
					<string>"</string>
					<key>end</key>
					<string>"</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>constant.character.escape.omegasl</string>
							<key>match</key>
							<string>\\.</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>numbers</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.numeric.float.omegasl</string>
					<key>match</key>
					<string>\b(?:\d+\.\d*|\.\d+)(?:[eE][+\-]?\d+)?f?\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.numeric.float.omegasl</string>
					<key>match</key>
					<string>\b\d+[eE][+\-]?\d+f?\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.numeric.integer.omegasl</string>
					<key>match</key>
					<string>\b\d+u?\b</string>
				</dict>
			</array>
		</dict>
		<key>shader-declarations</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.function.shader.omegasl</string>
					<key>match</key>
					<string>\b(vertex|fragment|compute|hull|domain)\b(?:\s*\([^)]*\))?\s+((?:void|bool|int|uint|float|double|(?:int|uint|float|double)(?:2|3|4)|float(?:2x2|2x3|2x4|3x2|3x3|3x4|4x2|4x3|4x4)|[A-Za-z_][A-Za-z0-9_]*))\s+([A-Za-z_][A-Za-z0-9_]*)\s*(?=\()</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.function.shader.omegasl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>storage.type.return-type.omegasl</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.shader.omegasl</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>struct-declarations</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.struct.omegasl</string>
					<key>match</key>
					<string>\b(struct)\s+([A-Za-z_][A-Za-z0-9_]*)(?:\s+(internal))?\b</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.struct.omegasl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.struct.omegasl</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.omegasl</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>resource-declarations</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.resource.buffer.omegasl</string>
					<key>match</key>
					<string>\b(buffer)\s*(&lt;)\s*([A-Za-z_][A-Za-z0-9_]*)\s*(&gt;)\s+([A-Za-z_][A-Za-z0-9_]*)\s*(:)\s*(\d+)\b</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.resource.omegasl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.generic.begin.omegasl</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.omegasl</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.generic.end.omegasl</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>variable.other.resource.omegasl</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.annotation.omegasl</string>
						</dict>
						<key>7</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.integer.decimal.omegasl</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.resource.texture-sampler.omegasl</string>
					<key>match</key>
					<string>\b(texture1d|texture2d|texture3d|sampler1d|sampler2d|sampler3d)\b\s+([A-Za-z_][A-Za-z0-9_]*)\s*(?::\s*(\d+))?</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.resource.omegasl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.other.resource.omegasl</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.integer.decimal.omegasl</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>resource-map</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.resource-map.omegasl</string>
					<key>begin</key>
					<string>\[</string>
					<key>end</key>
					<string>\]</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.brackets.begin.omegasl</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.brackets.end.omegasl</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>keyword.control.resource-access.omegasl</string>
							<key>match</key>
							<string>\binout|in|out\b</string>
						</dict>
						<dict>
							<key>name</key>
							<string>variable.other.resource.omegasl</string>
							<key>match</key>
							<string>\b[A-Za-z_][A-Za-z0-9_]*\b</string>
						</dict>
						<dict>
							<key>name</key>
							<string>punctuation.separator.comma.omegasl</string>
							<key>match</key>
							<string>,</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>attributes</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.attribute.annotation.omegasl</string>
					<key>match</key>
					<string>(:)\s*(VertexID|InstanceID|Position|Color|TexCoord|GlobalThreadID|LocalThreadID|ThreadGroupID)\b</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.annotation.omegasl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.constant.attribute.omegasl</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.shader.decorator.property.omegasl</string>
					<key>match</key>
					<string>\b(domain|partitioning|outputtopology|outputcontrolpoints|filter|address_mode|max_anisotropy|x|y|z)\b(?=\s*=)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.decorator.omegasl</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>support.constant.decorator.omegasl</string>
					<key>match</key>
					<string>\blinear|point|anisotropic|wrap|clamp_to_edge|mirror|mirror_wrap|tri|quad|integer|fractional_even|fractional_odd|triangle_cw|triangle_ccw|line\b</string>
				</dict>
			</array>
		</dict>
		<key>keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>keyword.control.omegasl</string>
					<key>match</key>
					<string>\bif|else|for|while|return\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>storage.modifier.omegasl</string>
					<key>match</key>
					<string>\bstruct|internal|static\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>storage.type.function.shader.omegasl</string>
					<key>match</key>
					<string>\bvertex|fragment|compute|hull|domain\b</string>
				</dict>
			</array>
		</dict>
		<key>types</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>storage.type.primitive.omegasl</string>
					<key>match</key>
					<string>\b(?:float(?:2x2|2x3|2x4|3x2|3x3|3x4|4x2|4x3|4x4)|(?:int|uint|float|double)(?:2|3|4)|void|bool|int|uint|float|double)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>storage.type.resource.omegasl</string>
					<key>match</key>
					<string>\bbuffer|texture1d|texture2d|texture3d|sampler1d|sampler2d|sampler3d\b</string>
				</dict>
			</array>
		</dict>
		<key>builtins</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>support.function.constructor.omegasl</string>
					<key>match</key>
					<string>\bmake_(?:float(?:2|3|4|2x2|2x3|2x4|3x2|3x3|3x4|4x2|4x3|4x4)|int(?:2|3|4)|uint(?:2|3|4))\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>support.function.builtin.omegasl</string>
					<key>match</key>
					<string>\b(?:sample|read|write|dot|cross|sin|cos|tan|asin|acos|atan|atan2|sqrt|abs|floor|ceil|round|frac|exp|exp2|log|log2|normalize|length|pow|min|max|step|reflect|clamp|lerp|smoothstep)\b</string>
				</dict>
			</array>
		</dict>
		<key>constants</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.language.boolean.omegasl</string>
					<key>match</key>
					<string>\b(?:true|false)\b</string>
				</dict>
			</array>
		</dict>
		<key>member-access</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>variable.other.member.omegasl</string>
					<key>match</key>
					<string>(?&lt;=\.)[A-Za-z_][A-Za-z0-9_]*\b</string>
				</dict>
			</array>
		</dict>
		<key>function-calls</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>entity.name.function.omegasl</string>
					<key>match</key>
					<string>\b([A-Za-z_][A-Za-z0-9_]*)\s*(?=\()</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.omegasl</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>operators</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>keyword.operator.omegasl</string>
					<key>match</key>
					<string>(?:\+\+|--|\+=|-=|\*=|/=|==|!=|&lt;=|&gt;=|&amp;&amp;|\|\||[-+*/=!&lt;&gt;])</string>
				</dict>
			</array>
		</dict>
		<key>punctuation</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>punctuation.accessor.omegasl</string>
					<key>match</key>
					<string>\.</string>
				</dict>
				<dict>
					<key>name</key>
					<string>punctuation.separator.comma.omegasl</string>
					<key>match</key>
					<string>,</string>
				</dict>
				<dict>
					<key>name</key>
					<string>punctuation.terminator.statement.omegasl</string>
					<key>match</key>
					<string>;</string>
				</dict>
				<dict>
					<key>name</key>
					<string>punctuation.section.group.begin.omegasl</string>
					<key>match</key>
					<string>[({]</string>
				</dict>
				<dict>
					<key>name</key>
					<string>punctuation.section.group.end.omegasl</string>
					<key>match</key>
					<string>[)}]</string>
				</dict>
			</array>
		</dict>
	</dict>
</dict>
</plist>
