#include "GTEBuiltinShaders.h"
#include "../omegasl/src/ShaderArchive.h"

#include <cstring>
#include <iostream>
#include <sstream>

_NAMESPACE_BEGIN_

// Generated by EmbedOmegaSLLib.cmake from the merged
// GTEBuiltinShaders.omegasllib (gte/CMakeLists.txt).
extern const unsigned char GTEBuiltinShaders_data[];
extern const std::size_t GTEBuiltinShaders_size;

namespace GTEBuiltinShaders {

namespace {

const omegasl::OmegaSLShaderArchive &archive() {
    static const omegasl::OmegaSLShaderArchive parsed = [] {
        omegasl::OmegaSLShaderArchive out;
        std::string bytes(reinterpret_cast<const char *>(GTEBuiltinShaders_data),
                          GTEBuiltinShaders_size);
        std::istringstream in(bytes);
        std::string err;
        if (!omegasl::ReadShaderArchive(in, out, err)) {
            std::cerr << "[GTEBuiltinShaders] failed to parse embedded library: "
                      << err << std::endl;
        }
        return out;
    }();
    return parsed;
}

} // namespace

const omegasl_shader *find(const char *name) {
    for (const auto &s : archive().shaders) {
        if (s.name != nullptr && std::strcmp(s.name, name) == 0) {
            return &s;
        }
    }
    return nullptr;
}

} // namespace GTEBuiltinShaders

_NAMESPACE_END_
