# Converts a compiled `.omegasllib` binary into a C++ translation unit that
# exposes its bytes as a `const unsigned char[]` + size, so OmegaGTE can ship
# a built-in shader library with no runtime filesystem dependency
# (Triangulation-Engine-Completion-Plan.md Phase 4.2). Pure CMake (file(READ
# ... HEX) + a regex pass) -- no external tool (xxd/bin2c/python) required on
# any platform.
#
# Usage: cmake -DIN=<path-to-.omegasllib> -DOUT=<path-to-.cpp> -DSYMBOL=<name> -P EmbedOmegaSLLib.cmake
# Emits, in the OmegaGTE namespace:
#   extern const unsigned char <SYMBOL>_data[];
#   extern const std::size_t   <SYMBOL>_size;

if(NOT DEFINED IN OR NOT DEFINED OUT OR NOT DEFINED SYMBOL)
    message(FATAL_ERROR "EmbedOmegaSLLib.cmake requires -DIN=<path> -DOUT=<path> -DSYMBOL=<name>")
endif()

file(READ "${IN}" _hex HEX)
string(LENGTH "${_hex}" _hexlen)
math(EXPR _n "${_hexlen} / 2")
string(REGEX REPLACE "(..)" "0x\\1," _bytes "${_hex}")

file(WRITE "${OUT}"
"// Auto-generated by EmbedOmegaSLLib.cmake from ${IN}. Do not edit.
#include <cstddef>

namespace OmegaGTE {
extern const unsigned char ${SYMBOL}_data[] = { ${_bytes} };
extern const std::size_t ${SYMBOL}_size = ${_n};
}
")
