#include "wrapper_gen.h"
#include <fstream>

namespace OmegaWrapGen {
    class PythonGen final : public Gen {
        PythonGenSettings & settings;
        GenContext *context;
        std::ofstream out;
        unsigned decl_count = 0;
    public:
        explicit PythonGen(PythonGenSettings & settings):settings(settings),context(nullptr){

        }
        GenContext & getContext() override {
            return *context;
        }
        void setContext(GenContext &ctxt) override {
            context = &ctxt;
            auto output_file = std::string(ctxt.output_dir).append("/").append(ctxt.name).append(".py");
            out.open(output_file,std::ios::out);
            out << "# " << COMMENT_HEADER << "\n";
            out << "# Python wrapper skeleton generated by omega-wrapgen\n\n";
        }
        void consumeDecl(DeclNode *node) override {
            (void)node;
            ++decl_count;
        }
        void finish() override {
            if(out.is_open()){
                out << "DECL_COUNT = " << decl_count << "\n";
                out.close();
            }
        }
    };

    Gen *Gen::CreatePythonGen(PythonGenSettings &settings) {
        return new PythonGen(settings);
    }
}
