#include "ast.h"
#include <memory>
#include <deque>

#ifndef OMEGA_WRAPGEN_WRAPPER_GEN_H
#define OMEGA_WRAPGEN_WRAPPER_GEN_H

#define COMMENT_HEADER "WARNING.. This file was generated by omega-wrapgen. DO NOT EDIT!"
#define HEADER_INSERT_TEMPLATE "#include \"@{0}\""

namespace OmegaWrapGen {

    struct GenContext {
        OmegaCommon::String name;
        OmegaCommon::StrRef output_dir;
    };

    struct CGenSettings {
        typedef enum : int {
            Retain,
            CamelCase,
            Kebab
        } NameCase;
        NameCase nameCase;
//        OmegaCommon::StrRef headerName;
    };

    struct PythonGenSettings {
        bool submoduleForCXXNamespace;
    };

    struct GoGenSettings {
        
    };

    struct JavaGenSettings {

    };

    struct SwiftGenSettings {
        
    };

    struct RustGenSettings {

    };


    class Gen : public TreeConsumer {
        friend class Parser;
    public:
        inline std::string generateCXXName(OmegaCommon::StrRef declName, TreeScope *scope){
            std::ostringstream out;
            std::deque<OmegaCommon::StrRef> scopes;
            TreeScope *cursor = scope;
            while(cursor && cursor != GLOBAL_SCOPE){
                if(cursor->type == TreeScope::Namespace || cursor->type == TreeScope::Class){
                    scopes.push_front(cursor->name);
                }
                cursor = cursor->parentScope;
            }

            for(auto & s : scopes){
                out << s << "::";
            }
            out << declName;
            return out.str();
        };
        using TreeConsumer::consumeDecl;
        virtual void setContext(GenContext & ctxt) = 0;
        virtual GenContext & getContext() = 0;
        virtual void finish() = 0;
        virtual ~Gen() = default;

        static Gen *CreateCGen(CGenSettings & settings);
        static Gen *CreatePythonGen(PythonGenSettings & settings);
        static Gen *CreateGoGen(GoGenSettings & settings);
        static Gen *CreateJavaGen(JavaGenSettings & settings);
        static Gen *CreateSwiftGen(SwiftGenSettings & settings);
        static Gen *CreateRustGen(RustGenSettings & settings);
    };



};

#endif
